server:
  port: 5050

spring:
  application:
    name: springbootZuulService


eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:5000/eureka/

zuul:
  routes:
    sbService :
      path : /sbService/**
      serviceId : springbootService